[package]
name = "markotd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
colored = "2.0.0"
dirs = "4.0.0"
hostname = "0.3.1"
itertools = "0.10.5"
once_cell = "1.16.0"
regex = "1.7.0"
systemstat = "0.2.2"
thiserror = "1.0.37"
which = "4.3.0"
whoami = "1.2.3"

[dev-dependencies]
assert_fs = "1.0.9"
filetime = "0.2.18"
