[package]
name = "markotd"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1"
chrono = "0.4"
color-eyre = "0.6.2"
colored = "2.1"
dirs = "5.0"
dotenvy = "0.15"
filetime = "0.2"
fs-err = "2.11"
hostname = "0.3"
itertools = "0.12"
once_cell = "1.19"
regex = "1.10"
systemstat = "0.2"
which = "6.0"
whoami = "1.4"

[dev-dependencies]
assert_fs = "1.0"
