[package]
name = "markotd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
colored = "2.1"
dirs = "5.0"
filetime = "0.2"
hostname = "0.3"
itertools = "0.12"
once_cell = "1.19"
regex = "1.10"
systemstat = "0.2"
thiserror = "1.0"
which = "6.0"
whoami = "1.4"

[dev-dependencies]
assert_fs = "1.0"
