#!/bin/sh
#
# Prints welcome, including
#
# * hostname
# * username
# * distro

distribution="$(lsb_release -ds 2> /dev/null)"

printf "%s# " "$EMPH"

if [ -n "$distribution" ]; then
    # shellcheck disable=SC3028
    printf "%s on %s" "$distribution" "$(hostname)"
else
    # shellcheck disable=SC3028
    printf "%s" "$(hostname)"
fi

printf "%s\n\nThe current user is %s.\n" "$RESET" "$USER"
