#!/bin/sh
# Prints links from ~/.motd-links
#
# Expects a file with a pair of <name>:<link> on each line.
#
# Example:
#
#   Syncthing:https://sleipnir.no-ip.net/syncthing
#   Gitea:https://sleipnir.no-ip.net/gitea

. ./common.sh

FILES="$HOME/.markotd-links ./markotd-links.test"

get_file() {
    for filename in $FILES; do
        if [ -f "$filename" ]; then
            echo "$filename"
            return 0
        fi
    done

    return 1
}

# Reads lines from stdin and prints the length of the longest line.
get_longest() {
    max_length=0

    while read -r line; do
        if [ "${#line}" -gt "$max_length" ]; then
            max_length=${#line}
        fi
    done

    echo "$max_length"
}

# Prints a name and an URL like a Markdown link.
#
# $1: name
# $2: URL
# $3: optional width of name
print_url() {
    name="[$1"
    printf " * %${3:-0}s](%s)\n" "$name" "$2"
}

if FILE=$(get_file); then
    lines=$(read_lines < "$FILE")

    max_width=$(echo "$lines" | cut -d : -f 1 | get_longest)
    max_width=$((max_width + 1))


    echo "$lines" | while IFS=: read -r name link; do
        print_url "$name" "$link" "$max_width"
    done

    echo
fi
