#!/bin/sh
# Prints links from ~/.motd-links
#
# Expects a file with a pair of <name>:<link> on each line.
#
# Example:
#
#   Syncthing:https://sleipnir.no-ip.net/syncthing
#   Gitea:https://sleipnir.no-ip.net/gitea

FILENAME="markotd-links"
FILES="$HOME/.$FILENAME"

if [ -n "$DEBUG" ]; then
    FILES="$FILES ./$FILENAME.test"
fi

# Reads lines from stdin and prints the length of the longest line.
get_longest() {
    max_length=0

    while read -r line; do
        if [ "${#line}" -gt "$max_length" ]; then
            max_length=${#line}
        fi
    done

    printf "%s ""$max_length"
}

# Prints a name and an URL like a Markdown link.
#
# $1: name
# $2: URL
# $3: optional width of name
print_url() {
    name="[$1"
    printf " * %${3:-0}s](%s)\n" "$name" "$2"
}

if file=$(get_file "$FILES"); then
    printf "\n%s## Useful Links%s\n\n" "$EMPH" "$RESET"

    lines=$(read_lines < "$file")

    max_width=$(echo "$lines" | cut -d : -f 1 | get_longest)
    max_width=$((max_width + 1))

    echo "$lines" | while IFS=: read -r name link; do
        print_url "$name" "$link" "$max_width"
    done
fi
