#!/bin/sh

apt_file="/var/cache/apt/pkgcache.bin"

if command -v apt > /dev/null || [ -n "$DEBUG" ]; then
    if [ -n "$DEBUG" ]; then
        apt_file="./apt.test"
    fi

    if [ ! -f "$apt_file" ]; then
        printf '\n%sUnable to read %s%s\n\n' "$EMPH" "$apt_file" "$RESET"
    else
        seconds_since_last_update=$(stat $apt_file -c '%Y')

        if [ "$(hours_since "@$seconds_since_last_update")" -gt "$NOTIFY_AFTER_HOURS" ]; then
            printf '\n%sAPT last updated on %s%s\n\n' "$EMPH" "$(date -d "@$seconds_since_last_update")" "$RESET"

            pretty_print_time_since_date "$seconds_since_last_update"
        fi
    fi
fi
