#!/bin/sh

pacman_file="/var/log/pacman.log"

if command -v pacman > /dev/null || [ -n "$DEBUG" ]; then

    if [ -n "$DEBUG" ]; then
        pacman_file="./pacman.test"
    fi



    if [ ! -f "$pacman_file" ]; then
        printf '\n%sUnable to read %s%s\n\n' "$EMPH" "$pacman_file" "$RESET"

    else
        last_update_date=$(grep 'starting full system upgrade' "$pacman_file" | tail -1 | cut -d " " -f 1 | sed 's/^.\(.*\).$/\1/')

        if [ "$(hours_since "$last_update_date")" -gt "$NOTIFY_AFTER_HOURS" ]; then
            printf '\n%sLast updated on %s%s\n\n' "$EMPH" "$(date -d "$last_update_date")" "$RESET"

            pretty_print_time_since_date "$last_update_date"
        fi
    fi

fi
