#!/bin/sh

if command -v pacman || [ -n "$DEBUG" ]; then
    input_file="/var/log/pacman.log"

    if [ -n "$DEBUG" ]; then
        input_file="./pacman.test"
    fi

    last_update_date=$(grep 'starting full system upgrade' "$input_file" | tail -1 | cut -d " " -f 1)
    last_update_date="${last_update_date%?}"
    last_update_date="${last_update_date#?}"

    if [ "$(hours_since "$last_update_date")" -gt "$NOTIFY_AFTER_HOURS" ]; then
        printf '\n%sLast updated on %s%s\n\n' "$EMPH" "$(date -d "$last_update_date")" "$RESET"

        printf 'It has been %s.\n' "$(pretty_print_time_since_date "$last_update_date")"
    fi
fi
