#!/bin/sh

pacman_file="/var/log/pacman.log"

if command -v pacman > /dev/null || [ -n "$DEBUG" ]; then
    if [ -n "$DEBUG" ]; then
        pacman_file="./pacman.test"
    fi

    if [ ! -f "$pacman_file" ]; then
        printf '\n%sUnable to read %s%s\n\n' "$EMPH" "$pacman_file" "$RESET"

    else
        last_update_date=$(grep 'starting full system upgrade' "$pacman_file" | tail -1 | cut -d " " -f 1 | sed 's/^.\(.*\).$/\1/')

        seconds_since_last_update=$(date -d "$last_update_date" +%s)

        if [ "$(hours_since "$seconds_since_last_update")" -gt "$NOTIFY_AFTER_HOURS" ]; then
            printf '\n%sPacMan last updated on %s%s\n\n' "$EMPH" "$(date -d "@$seconds_since_last_update")" "$RESET"

            pretty_print_time_since_date "$seconds_since_last_update"
        fi
    fi

fi
